# Generated by Django 6.0.1 on 2026-01-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortecaja',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cortecaja',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
