# Generated by Django 6.0.1 on 2026-01-17 18:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_cliente_historialdescuento_and_more'),
        ('sucursales', '0002_alter_sucursal_options_sucursal_ciudad_and_more'),
        ('ventas', '0002_alter_cortecaja_fecha_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cortecaja',
            options={'ordering': ['-fecha_inicio'], 'permissions': [('puede_cerrar_corte', 'Puede cerrar cortes de caja'), ('puede_verificar_corte', 'Puede verificar cortes de caja'), ('puede_ver_todos_cortes', 'Puede ver todos los cortes de caja')], 'verbose_name': 'Corte de Caja', 'verbose_name_plural': 'Cortes de Caja'},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'permissions': [('puede_cancelar_venta', 'Puede cancelar ventas'), ('puede_ver_todas_ventas', 'Puede ver todas las ventas'), ('puede_ver_reportes', 'Puede ver reportes de ventas')], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cortes_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('verificado', 'Verificado')], default='abierto', max_length=20),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='folio',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Folio de Corte'),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='total_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='total_efectivo_esperado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='total_efectivo_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='total_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='total_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='ventas_incluidas',
            field=models.ManyToManyField(blank=True, related_name='cortes_caja', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cortes_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado por unidad', max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Precio con descuento aplicado', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='tiene_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='catalogos.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='efectivo_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Folio de Venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cortecaja',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_caja', to='sucursales.sucursal'),
        ),
        migrations.AlterField(
            model_name='cortecaja',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cortecaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio original del producto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='catalogos.productosucursal'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cortecaja',
            index=models.Index(fields=['folio'], name='ventas_cort_folio_4ce90b_idx'),
        ),
        migrations.AddIndex(
            model_name='cortecaja',
            index=models.Index(fields=['estado'], name='ventas_cort_estado_bb7814_idx'),
        ),
        migrations.AddIndex(
            model_name='cortecaja',
            index=models.Index(fields=['sucursal', 'fecha_inicio'], name='ventas_cort_sucursa_ba3469_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['venta'], name='ventas_deta_venta_i_4d5b25_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['producto'], name='ventas_deta_product_0f454d_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['folio'], name='ventas_vent_folio_f7143d_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='ventas_vent_fecha_8683f5_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente'], name='ventas_vent_cliente_1869ce_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='ventas_vent_estado_b0d674_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'fecha'], name='ventas_vent_sucursa_ac7253_idx'),
        ),
    ]
