# Generated by Django 6.0.1 on 2026-01-17 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_categoria_movimientoinventario_unidadmedida_and_more'),
        ('sucursales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='dias_operacion',
            field=models.CharField(default='Lunes a Viernes', max_length=100, verbose_name='Días de Operación'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='encargado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='horario_apertura',
            field=models.TimeField(default='08:00:00', verbose_name='Horario Apertura'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='horario_cierre',
            field=models.TimeField(default='18:00:00', verbose_name='Horario Cierre'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='pais',
            field=models.CharField(default='México', max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='permite_compras',
            field=models.BooleanField(default=True, verbose_name='Permite Compras'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='permite_ventas',
            field=models.BooleanField(default=True, verbose_name='Permite Ventas'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracionSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo_global', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Stock Mínimo Global')),
                ('stock_maximo_global', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Stock Máximo Global')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='% IVA')),
                ('redondeo_ventas', models.BooleanField(default=True, verbose_name='Redondear Ventas')),
                ('mostrar_stock', models.BooleanField(default=True, verbose_name='Mostrar Stock en Ventas')),
                ('max_intentos_login', models.IntegerField(default=3, verbose_name='Máx. Intentos de Login')),
                ('tiempo_bloqueo', models.IntegerField(default=15, verbose_name='Tiempo Bloqueo (minutos)')),
                ('generar_reporte_diario', models.BooleanField(default=True, verbose_name='Generar Reporte Diario')),
                ('hora_reporte', models.TimeField(default='22:00:00', verbose_name='Hora Reporte Diario')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='sucursales.sucursal')),
            ],
            options={
                'verbose_name': 'Configuración de Sucursal',
                'verbose_name_plural': 'Configuraciones de Sucursal',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Transferencia')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='sucursales.sucursal')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='sucursales.sucursal')),
                ('usuario_autoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia de Inventario',
                'verbose_name_plural': 'Transferencias de Inventario',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_enviada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sucursales.transferenciainventario')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalles de Transferencia',
                'unique_together': {('transferencia', 'producto')},
            },
        ),
    ]
